const steps = [
 ["1. Kasir mengunggah tracker", "Buka Impor CSV, pilih ekspor tracker V3BKS, lalu buat draf. Periksa jumlah pemasukan dan pengeluaran. Baris booking tanpa DP atau pelunasan tidak dihitung sebagai penerimaan."],
 ["2. Periksa setiap baris", "Lengkapi kategori dan rekening. Rekening yang tidak terbaca harus dipilih; aplikasi tidak menganggapnya sebagai Cash. Baris mirip ditandai untuk diperiksa dan baris identik dilewati."],
 ["3. Kirim ke finance", "Setelah pemetaan lengkap, kirim draf. Saldo tetap belum berubah. Finance dapat mengembalikan draf dengan catatan atau menyetujui pencatatan."],
 ["4. Finance menyetujui", "Buka unggahan yang menunggu. Cocokkan dengan tracker dan bukti. Jika angka berubah, pilih Koreksi dan transaksi lama yang diganti. Persetujuan mencatat pembayaran dan jurnal sekaligus."],
 ["5. Lampirkan bukti atau ajukan koreksi", "Menu Bukti & Catatan menerima JPG, PNG, atau PDF maksimal 2 MB. Pilih transaksi atau unggahan terkait. Catatan koreksi tidak langsung mengubah saldo; finance meninjau permintaan."],
 ["6. Hubungkan DP dan pelunasan", "Finance membuat data booking beserta harga total, kemudian menghubungkan pembayaran yang telah disetujui di menu Pembayaran. Menghubungkan pembayaran tidak mencatat penerimaan kedua."],
 ["7. Tutup kas", "Kasir menghitung uang tunai fisik, memilih tanggal dan rekening Cash, lalu mengirim tutup kas. Finance meninjau selisih. Selisih yang belum jelas tidak otomatis dijadikan biaya."],
 ["8. Rekonsiliasi & laporan", "Finance mencocokkan mutasi bank dengan pembayaran yang disetujui. Saran pencocokan perlu dikonfirmasi. Ringkasan arus kas menunjukkan uang masuk dikurangi uang keluar; angka ini berbeda dari laba akuntansi."],
 ["9. Saldo awal & transfer", "Di Daftar Rekening, masukkan saldo awal, tanggal, dan referensi bukti. Gunakan Transfer untuk perpindahan antar rekening sendiri agar tidak menjadi pemasukan atau pengeluaran usaha. Mutasi transfer bank masih perlu diperiksa manual."],
 ["10. Tutup periode", "Setelah saldo dan bukti sesuai, finance mengunci periode. Perubahan transaksi pada periode terkunci ditolak. Simpan ekspor laporan dan gunakan fasilitas cadangan database sebelum perubahan besar."],
];
export default function PanduanPage(){return <div className="max-w-3xl mx-auto space-y-5"><div><p className="text-brand-green text-sm">V3BKS Mini Soccer</p><h2 className="text-2xl font-bold mt-1">Panduan operasional</h2><p className="text-slate-400 mt-2">Gunakan tautan yang sama di Android, iPhone, tablet, dan desktop. Koneksi internet diperlukan. Kasir mendapatkan menu lapangan; finance dan owner mendapatkan laporan serta pemeriksaan.</p></div>{steps.map(([title,description])=><section key={title} className="card"><h3 className="font-semibold">{title}</h3><p className="text-slate-400 text-sm mt-2 leading-relaxed">{description}</p></section>)}<p className="text-sm text-slate-400">Tahap berikutnya: pencatatan langsung oleh kasir dan booking mandiri pelanggan. Versi ini memakai impor tracker sebagai sumber pembayaran utama.</p></div>}
