"use client";
import { useCallback, useEffect, useState } from "react";
import { formatRupiah } from "@/lib/format";
import type { ParsedRow } from "@/lib/v3bks-import";
import { STATUS } from "./ImportClient";
type Line = { id: string; sourceRow: number; payload: ParsedRow; decision: string; categoryId: string | null; accountId: string | null; replacesId: string | null; issue: string | null };
type Review = { batch: { id: string; fileName: string; status: string; reviewNote?: string; lines: Line[] }; canApprove: boolean; categories: { id: string; nama: string; tipe: string }[]; accounts: { id: string; nama: string }[]; previous: { id: string; tanggal: string; namaEntitas: string | null; jumlah: number; catatan: string | null; category: { nama: string }; account: { nama: string } }[] };
export default function ImportReview({ id }: { id: string }) {
 const [data, setData] = useState<Review | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [note, setNote] = useState("");
 const [dirty,setDirty]=useState<Record<string,boolean>>({});
 const hasUnsaved=Object.values(dirty).some(Boolean);
 const load = useCallback(async () => { const r = await fetch(`/api/imports/${id}`); const d = await r.json(); if (!r.ok) throw new Error(d.error); setData(d); }, [id]);
 useEffect(() => { load().catch(e => setError(String(e))); }, [load]);
 async function act(body: {action:string;lineId?:string;[key:string]:unknown}) { setBusy(true); setError(""); try { const r = await fetch(`/api/imports/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); await load(); if(body.lineId)setDirty(d=>({...d,[body.lineId!]:false})); } catch (e) { setError(e instanceof Error ? e.message : "Koneksi gagal. Periksa status sebelum mencoba lagi."); } finally { setBusy(false); } }
 if (!data) return <p role="status">{error || "Memuat pemeriksaan…"}</p>;
 const { batch } = data; const editable = !["approved", "rejected"].includes(batch.status) && (batch.status !== "submitted" || data.canApprove);
 const totals = batch.lines.filter(l => ["new", "replace"].includes(l.decision)).reduce((s,l) => { s[l.payload.tipe] += l.payload.jumlah; return s; }, {income:0,expense:0});
 return <div className="space-y-5 max-w-6xl mx-auto"><section className="card"><p className="text-brand-green text-sm">{STATUS[batch.status]}</p><h2 className="text-xl font-bold break-words mt-2">{batch.fileName}</h2><a className="text-sm underline text-slate-400" href={`/api/imports/${id}?download=1`}>Unduh CSV sumber</a><p className="text-sm mt-3">Dipilih: pemasukan {formatRupiah(totals.income)} · pengeluaran {formatRupiah(totals.expense)}</p><p className="text-xs text-slate-400 mt-2">Baris yang hilang dari tracker tidak menghapus transaksi lama. Pilih koreksi hanya jika pembayaran yang sama memang berubah.</p>{batch.reviewNote && <p className="text-brand-amber mt-3">Catatan finance: {batch.reviewNote}</p>}</section>
 {error && <p role="alert" className="card text-brand-red">{error}</p>}
 {batch.lines.map(line => <LineCard key={line.id + batch.status} line={line} data={data} disabled={!editable || busy} onDirty={()=>setDirty(d=>({...d,[line.id]:true}))} save={value => act({action:"line",lineId:line.id,...value})} />)}
 <section className="card space-y-3 sticky bottom-2 shadow-xl border-brand-green/20">{hasUnsaved && <p role="status" className="text-brand-amber text-sm">Simpan keputusan setiap baris yang diubah sebelum melanjutkan.</p>}{!["approved","rejected","submitted"].includes(batch.status) && <button className="btn-primary min-h-12" disabled={busy || hasUnsaved} onClick={() => act({action:"submit"})}>Kirim untuk diperiksa finance</button>}
 {batch.status === "submitted" && data.canApprove && <><p className="text-sm">Persetujuan akan memasukkan transaksi terpilih ke saldo dan laporan.</p><button className="btn-primary min-h-12" disabled={busy || hasUnsaved} onClick={() => act({action:"approve"})}>Setujui dan catat transaksi</button><label className="block text-sm">Alasan pengembalian / penolakan<textarea className="input mt-2" value={note} onChange={e => setNote(e.target.value)} /></label><div className="flex gap-2"><button className="btn-ghost" disabled={busy || !note.trim()} onClick={() => act({action:"return",note})}>Kembalikan</button><button className="btn-ghost text-brand-red" disabled={busy || !note.trim()} onClick={() => act({action:"reject",note})}>Tolak</button></div></>}
 {busy && <p role="status">Menyimpan… Jangan tutup halaman.</p>}{batch.status === "approved" && <p className="text-brand-green">Transaksi telah disetujui dan masuk laporan.</p>}</section></div>;
}
function LineCard({line,data,disabled,save,onDirty}:{line:Line;data:Review;disabled:boolean;onDirty:()=>void;save:(v:object)=>void}) {
 const [categoryId,setCat]=useState(line.categoryId || ""),[accountId,setAcc]=useState(line.accountId || ""),[decision,setDecision]=useState(line.decision),[replacesId,setReplace]=useState(line.replacesId || "");
 const row=line.payload;
 return <section className="card space-y-3"><div className="flex justify-between gap-3"><div><p className="text-xs text-slate-500">Baris CSV {line.sourceRow} · {row.tanggal}</p><h3 className="font-semibold">{row.entitas || row.tempatBeli || row.kategori}</h3><p className="text-sm text-slate-400">{row.kategori} · {row.statusBayar || "Pengeluaran"}</p></div><strong className={row.tipe === "income" ? "text-brand-green" : "text-brand-red"}>{formatRupiah(row.jumlah)}</strong></div><p className="text-sm break-words">{row.catatan}</p>{line.issue && <p className="text-brand-amber text-xs">{line.issue}</p>}
 <div className="grid sm:grid-cols-3 gap-3"><label className="text-xs">Kategori<select disabled={disabled} className="input mt-1" value={categoryId} onChange={e=>{setCat(e.target.value);onDirty();}}><option value="">Pilih kategori</option>{data.categories.filter(c=>c.tipe===row.tipe).map(c=><option key={c.id} value={c.id}>{c.nama}</option>)}</select></label><label className="text-xs">Rekening<select disabled={disabled} className="input mt-1" value={accountId} onChange={e=>{setAcc(e.target.value);onDirty();}}><option value="">Pilih rekening</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.nama}</option>)}</select></label><label className="text-xs">Keputusan<select disabled={disabled} className="input mt-1" value={decision} onChange={e=>{setDecision(e.target.value);onDirty();}}><option value="review">Periksa dahulu</option><option value="new">Transaksi baru</option><option value="skip">Lewati / sudah tercatat</option>{data.canApprove && <option value="replace">Koreksi transaksi lama</option>}</select></label></div>
 {decision === "replace" && <label className="block text-xs">Transaksi yang dikoreksi<select className="input mt-1" disabled={disabled} value={replacesId} onChange={e=>{setReplace(e.target.value);onDirty();}}><option value="">Pilih transaksi lama</option>{data.previous.map(p=><option key={p.id} value={p.id}>{p.tanggal.slice(0,10)} · {p.namaEntitas || p.category.nama} · {p.account.nama} · {formatRupiah(p.jumlah)} · {p.catatan}</option>)}</select></label>}
 {!disabled && <button className="btn-ghost min-h-11" onClick={()=>save({categoryId,accountId,decision,replacesId})}>Simpan keputusan baris</button>}</section>;
}
