"use client";
import { useEffect, useState } from "react";
import { formatRupiah } from "@/lib/format";
type Data={items:{id:string;text:string;authorName:string;kind:string;status:string;resolution?:string}[];transactions:{id:string;tanggal:string;namaEntitas:string|null;jumlah:number;category:{nama:string}}[];batches:{id:string;fileName:string}[];evidence:{id:string;name:string}[];canReview:boolean};
export default function Operations(){
 const [data,setData]=useState<Data|null>(null),[text,setText]=useState(""),[ref,setRef]=useState(""),[kind,setKind]=useState("note"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[resolution,setResolution]=useState<Record<string,string>>({});
 async function load(){const r=await fetch("/api/operations");const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);}
 useEffect(()=>{load().catch(e=>setError(String(e)));},[]);
 const references=()=>ref.startsWith("tx:")?{transactionId:ref.slice(3)}:ref.startsWith("batch:")?{importBatchId:ref.slice(6)}:{};
 async function send(url:string,method:string,body:object|FormData){setBusy(true);setError("");try{const r=await fetch(url,{method,...(body instanceof FormData?{body}:{headers:{"Content-Type":"application/json"},body:JSON.stringify(body)})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();return true;}catch(e){setError(e instanceof Error?e.message:"Koneksi gagal. Isian tetap tersedia.");return false;}finally{setBusy(false);}}
 return <div className="max-w-4xl mx-auto space-y-5"><h2 className="text-2xl font-bold">Bukti & pengajuan koreksi</h2><p className="text-sm text-slate-400">Catatan dan bukti membantu finance memeriksa transaksi. Pengajuan koreksi belum mengubah saldo.</p>{error&&<p role="alert" className="text-brand-red">{error}</p>}<section className="card space-y-4"><label className="block text-sm">Referensi<select className="input mt-2" value={ref} onChange={e=>setRef(e.target.value)}><option value="">Catatan umum</option><optgroup label="Unggahan tracker">{data?.batches.map(b=><option key={b.id} value={`batch:${b.id}`}>{b.fileName}</option>)}</optgroup><optgroup label="Transaksi">{data?.transactions.map(t=><option key={t.id} value={`tx:${t.id}`}>{t.tanggal.slice(0,10)} · {t.namaEntitas||t.category.nama} · {formatRupiah(t.jumlah)}</option>)}</optgroup></select></label><label className="block text-sm">Jenis<select className="input mt-2" value={kind} onChange={e=>setKind(e.target.value)}><option value="note">Keterangan / bukti</option><option value="correction">Pengajuan koreksi</option></select></label><label className="block text-sm">Keterangan<textarea className="input mt-2 min-h-28" value={text} onChange={e=>setText(e.target.value)} placeholder="Jelaskan transaksi, perbedaan, dan koreksi yang diperlukan."/></label><button disabled={busy||!text.trim()} className="btn-primary min-h-12" onClick={async()=>{if(await send("/api/operations","POST",{text,kind,...references()}))setText("");}}>Kirim catatan</button><label className="block text-sm">Lampirkan bukti (JPG, PNG, PDF; maks. 2 MB)<input type="file" className="block mt-2 w-full" disabled={busy||!ref} accept="image/jpeg,image/png,application/pdf" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;const form=new FormData();form.set("file",f);Object.entries(references()).forEach(([k,v])=>form.set(k,v));await send("/api/evidence","POST",form);e.target.value="";}}/></label></section>
 <section className="space-y-3"><h3 className="font-semibold">Riwayat pemeriksaan</h3>{data?.items.map(n=><article className="card" key={n.id}><p className="text-xs text-brand-green">{n.authorName} · {n.kind==="correction"?"Koreksi":"Catatan"} · {n.status==="reviewed"?"Diperiksa":"Menunggu"}</p><p className="mt-2 whitespace-pre-wrap">{n.text}</p>{n.resolution&&<p className="mt-2 text-sm text-slate-400">Finance: {n.resolution}</p>}{data.canReview&&n.status!=="reviewed"&&<div className="mt-3 space-y-2"><textarea aria-label="Hasil pemeriksaan" className="input" value={resolution[n.id]||""} onChange={e=>setResolution({...resolution,[n.id]:e.target.value})}/><button className="btn-ghost" disabled={busy||!resolution[n.id]?.trim()} onClick={()=>send("/api/operations","PATCH",{id:n.id,resolution:resolution[n.id]})}>Simpan hasil pemeriksaan</button></div>}</article>)}</section><section className="card"><h3 className="font-semibold">Bukti terlampir</h3>{data?.evidence.map(e=><a className="block mt-3 underline break-words" key={e.id} href={`/api/evidence/${e.id}`}>{e.name}</a>)}</section></div>;
}
