"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
type Account={id:string;nama:string;saldoAwal:number;openingDate:string;openingEvidence:string};
export default function Treasury({accounts}:{accounts:Account[]}){
 const router=useRouter();const [action,setAction]=useState("transfer"),[accountId,setAccount]=useState(accounts[0]?.id||""),[to,setTo]=useState(""),[amount,setAmount]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[note,setNote]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[requestId,setRequestId]=useState("");
 async function submit(){setBusy(true);setError("");const key=requestId||crypto.randomUUID();setRequestId(key);try{const r=await fetch("/api/treasury",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,accountId,from:accountId,to,amount,date,note,requestId:key})});const d=await r.json();if(!r.ok)throw new Error(d.error);setError("Tersimpan.");setRequestId("");setAmount("");setNote("");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Koneksi gagal. Periksa saldo sebelum mengulang.");}finally{setBusy(false);}}
 return <section className="card space-y-3"><h3 className="font-semibold">Saldo awal & transfer internal</h3><select aria-label="Jenis pengelolaan rekening" className="input" value={action} onChange={e=>setAction(e.target.value)}><option value="transfer">Transfer antar rekening</option><option value="opening">Tetapkan saldo awal</option></select><div className="grid sm:grid-cols-2 gap-3"><label className="text-sm">Rekening {action==="transfer"?"asal":""}<select className="input mt-1" value={accountId} onChange={e=>setAccount(e.target.value)}>{accounts.map(a=><option value={a.id} key={a.id}>{a.nama}</option>)}</select></label>{action==="transfer"&&<label className="text-sm">Rekening tujuan<select className="input mt-1" value={to} onChange={e=>setTo(e.target.value)}><option value="">Pilih rekening</option>{accounts.filter(a=>a.id!==accountId).map(a=><option value={a.id} key={a.id}>{a.nama}</option>)}</select></label>}<label className="text-sm">Tanggal berlaku<input type="date" className="input mt-1" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="text-sm">Nominal rupiah<input inputMode="decimal" type="number" min="0" className="input mt-1" value={amount} onChange={e=>setAmount(e.target.value)}/></label></div><label className="block text-sm">Sumber konfirmasi / referensi bukti<input className="input mt-1" value={note} onChange={e=>setNote(e.target.value)}/></label>{action==="opening"&&<p className="text-xs text-brand-amber">Saldo awal berlaku sebelum transaksi pertama. Sumber sebelumnya: {accounts.find(a=>a.id===accountId)?.openingEvidence||"Belum dikonfirmasi"}.</p>}<button className="btn-primary" disabled={busy||!note.trim()||!amount} onClick={submit}>{busy?"Menyimpan…":"Simpan"}</button>{error&&<p role="status" className="text-sm">{error}</p>}</section>;
}
